name: Release Bash Project

permissions: {}

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project folder name (e.g., bible, fluro-songs, ghpr)"
        required: true
        type: string
      version:
        description: "New version number (e.g., 1.0.1)"
        required: true
        type: string

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755
        with:
          deno-version: v2.x

      - name: Configure Git user
        id: git-user-config
        uses: Homebrew/actions/git-user-config@master
        with:
          username: bkdbot

      - name: Set up commit signing
        uses: Homebrew/actions/setup-commit-signing@master
        with:
          ssh: true
          signing_key: ${{ secrets.BKDBOT_SSH_SIGNING_KEY }}

      - name: Create Release
        id: create_release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          tag_name: ${{ inputs.project }}-${{ inputs.version }}
          name: Release ${{ inputs.project }}-${{ inputs.version }}
          draft: false
          prerelease: false
          files: |
            ${{ inputs.project }}/${{ inputs.project }}
