name: Test

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
        with:
          deno-version: 2.x

      - name: Run deno check
        run: |
          deno check .

      - name: Lint
        run: |
          deno lint

      - name: Check formatting
        run: |
          deno fmt --check

      - name: Test ghpr project
        working-directory: ./ghpr
        run: |
          deno test --allow-read --allow-net --allow-env

      - name: Test bible project
        working-directory: ./bible
        run: |
          deno test --allow-read --allow-net

      - name: Test fluro-songs project
        working-directory: ./fluro-songs
        run: |
          deno test --allow-read --allow-net --allow-env
